### PR TITLE
Unit 3

### PR DESCRIPTION
**Pull request by kathy-ramos**

### CODE REVIEW

**Comment by kathy-ramos** [comment]
Unit
ERWIN HOWARD HERRERA 18210716
KATHY ABIGAIL RAMOS ROBLES 17211556

 Evaluation Practice

**Comment by jcromerohdz** [comment]
Hello guys please fix the conflicts for this branch in order to continue with the review processs.

**Comment by ErwinHoward** [comment]
it is already corrected
@jcromerohdz

**Comment by jcromerohdz** [comment]
Nice @ErwinHoward please merge this branch into develop

**Pull request merged**
