### PR TITLE
Unit 4

### PR DESCRIPTION
**Pull request by kathy-ramos**
Final Proyect documentation
Howard Herrera Erwin - 18210716
Ramos Robles Kathy Abigail - 17211556

### CODE REVIEW

**Comment by jcromerohdz** [comment]
Hello guys please fix the conflicts for this branch in order to continue with the review process

**Comment by jcromerohdz** [comment]
You guys, need to resolve the conflicts of this branch, let me know whet this is done.

**Comment by ErwinHoward** [comment]
it is already corrected
@jcromerohdz

**Comment by jcromerohdz** [comment]
Nice @ErwinHoward please merge this branch into develop

**Pull request merged**
